#!/bin/sh
# Syncs repositories and downloads updates, meant to be run as a cronjob.

#sudo pacman -Rns $(pacman -Qtdq)

ping -q -c 1 1.1.1.1 > /dev/null || exit

notify-send -i "$PIX/larbs.svg" "Checking for pacakge updates..."

sudo pacman -Syyuw --noconfirm || notify-send "Error downloading updates.

Check your internet connection, if pacman is already running, or run update manually to see errors."
pkill -RTMIN+8 i3blocks

if pacman -Qu | grep -v "\[ignored\]"
then
	notify-send "🎁 Repository Sync" "Updates available. Click statusbar icon (📦) for update."
else
	notify-send "📦 Repository Sync"  "Sync complete. No new packages for update."
fi

notify-send -i "$PIX/larbs.gif" "Optimizing chromium database"
notify-send "`profile-cleaner c | grep reduced`"


